#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander')
  , colors = require('colors')
  , promptly = require('promptly')
  , exec = require('child_process').exec
  , execFile = require('child_process').execFile
  , spawn = require('child_process').spawn
  , _ = require('underscore')
  , fs = require('fs')
  , pathInfo = require('path')
  , async = require('async')
  , db = require('./app/core/database.js')
  , jf = require('jsonfile')
  , cache = require('memory-cache')
  , mongoose = require('mongoose')
  ;

colors.setTheme({
  silly: 'rainbow',
  input: 'grey',
  verbose: 'cyan',
  prompt: 'grey',
  info: 'cyan',
  data: 'grey',
  help: 'cyan',
  warn: 'yellow',
  debug: 'blue',
  error: 'red'
});

program
	.version('1.0.0');


program.on('--help', function(){

	var ASCII = new Buffer("\
		   ___  ___  ___  ___  ___  ___     _  _  ___    \n\
		  (  _)(_  )/ __)(  _)(  _)(   \\   ( )( )(__ \\   \n\
		   ) _) / / \\__ \\ ) _) ) _) ) ) )   \\\\// / __/   \n\
		  (___)(___)(___/(___)(___)(___/    (__) \\___)   \n\
		  									   \n\
	").toString();

	console.log(ASCII.yellow.bold);
	console.log("Made with love by ".magenta + "soyuka".bold.magenta);
	console.log("Big Thanks too : ".magenta + "Gaaa".rainbow +" (rutorrent), ".magenta +"Lines".rainbow +" (design), ".magenta +"Jay_kay".rainbow +" (ideas), ".magenta + "LeBedouin".rainbow +" ($$), ".magenta + "Winux".rainbow +", ".magenta + "H4T".rainbow +", ".magenta + "Ulule participants".rainbow +", ".magenta + "wouya (<3)".rainbow +" !".magenta)

	console.log(" ");
});

/**
 * Prompt validators
 * @type {Object}
 */
var validators = {
	user : function(v) {
		if(!v.match(/^[a-zA-Z0-9-_]{3,15}$/))
			throw new Error("Le nom d'utilisateur ne peut contenir que des caractères alphanumériques et des tirets".error);

		return v;
	},
	path : function(p) {
		if(!fs.existsSync(p))
			throw new Error("Le chemin spécifié n'est pas valide".error);

		return p;
	},
	ssl : function(ssl) {

		var nb = ssl.length, sslkeys = [];

		ssl = nb != 0 ? ssl.split(' ') : '';

		nb = ssl.length;

		if(nb == 2) {
			while(nb--) {
				var ext = pathInfo.extname(ssl[nb]);
				if(ext != '.pem' && ext != '.key')
					throw new Error("Il faut un fichier pem et un fichier key".error);
		
				sslkeys[nb] = {path : ssl[nb], ext: ext};
			}

		} else if(nb == 1)
			throw new Error("Il faut un fichier pem et un fichier key".error);
		
		if(sslkeys.length == 0)
			sslkeys = ssl;

		return sslkeys;
	}
};

/**
 * Torrent installer
 * @type {Object}
 */
var torrent = {
	rutorrent : function(done) {
		var shell_path = __dirname + '/app/scripts/rutorrent/install.sh';
		fs.chmodSync(shell_path, '775');
		
		var running = spawn(shell_path);

		running.stdout.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.log(string.info);
		});

		running.stderr.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.log(string.error);
			
		});

		running.on('exit', function (code) {
			console.log('Installation de rutorrent terminée'.info);
			var config = jf.readFileSync(__dirname + '/app/config.json');
			
			config.rutorrent = true;

			jf.writeFileSync(__dirname+'/app/config.json', config);

			done(null, 'rutorrent');
		});
	},
	transmission : function(done) {
		var shell_path = __dirname + '/app/scripts/transmission/install.sh';
		fs.chmodSync(shell_path, '775');
		
		var running = spawn(shell_path);

		running.stdout.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.log(string.info);
		});

		running.stderr.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.log(string.error);
		});

		running.on('exit', function (code) {
			console.log('Installation de transmission terminée'.info);

			var config = jf.readFileSync(__dirname + '/app/config.json');
			
			config.transmission = true;

			jf.writeFileSync(__dirname+'/app/config.json', config);

			done(null, 'transmission');
		});
	},
	aucun : function(done) {
		done(null,null);
	}
};

var userdel = {
	rutorrent : function(username, done) {
		var shell_path = __dirname + '/app/scripts/rutorrent/userdel.sh';
		fs.chmodSync(shell_path, '775');
		
		var running = spawn(shell_path, [username]);

		running.stdout.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.log(string.info);
		});

		running.stderr.on('data', function (data) {
			var string = new Buffer(data).toString();
			// if(cache.get('force') === true)
			 	console.log(string.error);
			// else
			// 	throw string.error;
		});

		running.on('exit', function (code) {
			db.users.delete(username, function(err) {
		 		console.log("Utilisateur "+ username + " supprimé".info);
		 		done(null, 'rutorrent');
		 	});
		});
	},
	transmission: function(username, done) {
		var shell_path =__dirname + '/app/scripts/transmission/userdel.sh';
		fs.chmodSync(shell_path, '775');

		var running = spawn(shell_path, [username]);

		running.stdout.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.log(string.info);
		});

		running.stderr.on('data', function (data) {
			var string = new Buffer(data).toString();
			//if(cache.get('force') === true)
				console.log(string.error);
			// else
			// 	throw string.error;
		});

		running.on('exit', function (code) {
			db.users.delete(username, function(err) {
		 		console.log("Utilisateur "+ username + " supprimé".info);
		 		done(null, 'transmission');
		 	});
		});
	},
	aucun: function(username, done) {
		db.users.delete(username, function(err) {
	 		console.log("Utilisateur "+ username + " supprimé".info);
	 		done(null, 'aucun');
	 	});
	}
};

var useradd = {
	aucun : function(username, password, done) {
		db.user.exists(username, function(exists) {
			if(exists)
				done("L'utilisateur existe déjà !", "aucun");
			else
				db.users.create({username : username, password: password, client : 'aucun', role : cache.get('role')}, function(err, user) {
		    		console.log("Utilisateur ajouté à la base de données d'ezseed".info);
		    		cache.put('user', {username : username, password : password});
		    		done(null,"aucun");
		    	});
	    });
	},
	rutorrent : function(username, password, done) {
		var shell_path =__dirname + '/app/scripts/rutorrent/useradd.sh';
		fs.chmodSync(shell_path, '775');

		var isInstall = cache.get('isinstall');

		var running = spawn(shell_path, [username, password])
		  , path = cache.get('path') ? cache.get('path') : '/home'
		  , userPath = pathInfo.join(path, username, 'downloads');

		running.stdout.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.log(string.info);
		});

		running.stderr.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.error(string.error);

		});

		running.on('exit', function (code) {
			db.user.exists(username, function(exists) {
				if(exists) {
					if(isInstall === true) {
						var u = cache.get('user');
						db.paths.save(userPath, u.username, function(err, p) {
							console.log("Chemin "+ userPath + " sauvegardé en base de données".info);
					 		done(null, 'rutorrent');
						});
					} else {
						console.log("L'utilisateur existe");
						done(null, 'rutorrent');
					}
				} else {
					db.users.create({username : username, password: password, client : 'rutorrent', role : cache.get('role')}, function(err, u) {
						db.paths.save(userPath, username, function(err, p) {
					 		console.log("Chemin "+ userPath + " sauvegardé en base de données".info);
					 		done(null, 'rutorrent');
					 	});
					});
				}
			});
		});
	},
	transmission : function(username, password, done) {
		var shell_path = __dirname + '/app/scripts/transmission/useradd.sh';
		fs.chmodSync(shell_path, '775');

		var isInstall = cache.get('isinstall');

		var running = spawn(shell_path, [username, password])
		  , path = cache.get('path') ? cache.get('path') : '/home'
		  , userPath = pathInfo.join(path, username, 'downloads');

		running.stdout.on('data', function (data) {
			var string = new Buffer(data).toString();
			console.log(string.info);
		});

		running.stderr.on('data', function (data) {
			var string = new Buffer(data).toString();

			if(cache.get('force') === true)
				console.log(string.error);
			else
				throw string.error;
		});

		running.on('exit', function (code) {
			console.log("Ajout de l'utilisateur tranmsission terminé, remplacement des configurations".info);
			var settings = __dirname + '/app/scripts/transmission/config/settings.'+username+'.json';

			fs.readFile(settings, function (err, data) {
				if (err) throw err;
				var d = JSON.parse(data);

				//Default settings replacement
				d['ratio-limit-enabled'] = true;
				d['incomplete-dir-enabled'] = true;
				d['incomplete-dir'] = pathInfo.join(path, username, 'incomplete');
				d['peer-port-random-on-start'] = true;
				d['lpd-enabled'] = true;
				d['peer-socket-tos'] = 'lowcost';
				d['rpc-password'] = password;
				d['rpc-enabled'] = true;
				d['rpc-whitelist-enabled'] = false;
				d['rpc-authentication-required'] = true;
				d['rpc-username'] = username;

				d['download-dir'] = userPath;

				db.users.count(function (err, count) {

					d['rpc-port'] = d['rpc-port'] + count + 1; //+1 because of transmission default, could be started on reboot by default

					fs.writeFileSync(settings, JSON.stringify(d));

					console.log('Démarage du daemon transmission'.info);

					fs.chmodSync(__dirname +'/app/scripts/transmission/daemon.sh', '775');

					exec('/etc/init.d/transmission-daemon-'+username + ' start',
				    	function(err, stdout, sdterr) {
				    		db.user.exists(username, function(exists) {
								if(exists) {
									if(isInstall === true) {
										var u = cache.get('user');
										db.paths.save(userPath, u.username, function(err, p) {
											console.log("Chemin "+ userPath + " sauvegardé en base de données".info);
									 		done(null, 'transmission');
										});
									} else {
										console.log("L'utilisateur existe");
										done(null, 'transmission');
									}
								} else {
							    	db.users.create({username : username, password: password, client : 'transmission', role : cache.get('role')}, function(err, u) {
							    		db.paths.save(userPath, username, function(err, p) {
							    			if(err)
							    				console.log(err.error);

									 		console.log("Chemin "+ userPath + " sauvegardé en base de données".info);
									 		done(null,'transmission');
									 	});
									});
								}
							});
						}
					);

				});
			});

		});
	}
		   
};



/**
 * Main install wrapper
 * @type {Object}
 */
var install = {
	admin_creation: function(callback){
		if(cache.get('skipuser'))
			callback(null, {});
		else {
			console.log("Entrez les informations de l'admin".info);

			promptly.prompt('Username : ', {validator: validators.user}, function (err, username) {
			    promptly.password('Password : ', function(err, password) {
			    	db.users.create({username : username, password: password, client : 'aucun', role: 'admin'}, function(err, user) {
			    		console.log("Utilisateur ajouté à la base de données d'ezseed".info);
			    		cache.put('user', {username : username, password : password});
			    		callback(null,{});
			    	});
			    });
			});
		}
	},
	save_path: function(callback){
		
		console.log("Le dossier ci-dessous sert à partager les fichiers avec nodejs, si vous n'êtes pas sûr laissez par défaut.".warn);

		promptly.prompt('Chemin des dossiers à parser [/home] :', {validator : validators.path, default: '/home'}, function(err, path) {

			var config = {
					"path": path,
					"fetchTime": 5000,
					"root": "",
					"location": "",
					"torrentLink": "embed",
					"diskSpace": "1048576",
					"availableSpace": "1 TB",
					"transmission":false,
  					"rutorrent":false,
					"theme": "default"
				};

			jf.writeFileSync(__dirname + '/app/config.json', config);

			console.log("Création d'un lien symbolique sur app/public/downloads".info);

			exec('ln -sfn '+ path +' ' + __dirname + '/app/public/downloads',
			  	function (error, stdout, stderr) {
			  		cache.put('path', path);
				    callback(null, {});
				}
			);
		});


	},
	nginx_conf: function(callback) {

		if(cache.get('skipnginx'))
			callback(null, {})
		else {

			console.log("ex : ./ssl.pem ./ssl.key - séparé par un espace (ou laissez vide pour la générer)".info);
			promptly.prompt("Entrez une clé SSL :", {validator : validators.ssl, default: ""}, function(err, sslkeys) {
				var l = sslkeys.length;

				if(!fs.existsSync('/usr/local/nginx'))
					fs.mkdirSync('/usr/local/nginx', '755');

				if(l == 2) {	
					var cmd = new Buffer("\
							mv " + sslkeys[0].path + " " + __dirname + "/ezseed" + sslkeys[0].ext + " && \
							mv " + sslkeys[1].path + " " + __dirname + "/ezseed" + sslkeys[1].ext + " && \
							mv *ezseed.key ezseed.pem* /usr/local/nginx/").toString();

					exec(cmd, function(error, stdout, stderr) {
						if(cache.get('force') === true && !_.isEmpty(stderr))
							console.log(stderr.error);
						else if(!_.isEmpty(stderr))
							throw stderr.error;

						exec("cat "+__dirname+"/app/scripts/nginx.conf > /etc/nginx/nginx.conf", function(error, stdout, stderr) {
							callback(null, {});
						});
					});
						 
				} else {
					var cmd = "openssl req -new -x509 -days 365 -nodes -out /usr/local/nginx/ezseed.pem -keyout /usr/local/nginx/ezseed.key -subj '/CN=ezseed/O=EzSeed/C=FR'";
					exec(cmd, function(error, stdout, stderr) {
						exec("cat "+__dirname+"/app/scripts/nginx.conf > /etc/nginx/nginx.conf && service nginx restart", function(error, stdout, stderr) {
							callback(null, {});
						});
					});
				}

			});
		}

	},
	client_torrent: function(callback, client) {
		if(client) {
			torrent[client](function(err, results) {
				callback(null, results);
			});
		} else {

			var choose = function(callback) {
				promptly.choose('Choisissez le client torrent à installer {rutorrent|transmission|[aucun]} : ', ['rutorrent', 'transmission', 'aucun'], {default : 'aucun'}, function (err, client) {
					if(client == 'aucun') {
						promptly.confirm("Êtes vous sûr de ne pas vouloir installer de client ? (l'utilisateur système ne sera pas créé) Y/n", {default : 'y'}, function (err, value) {
						    if(value === true) {
						    	torrent[client](function(err, results) {
							    	callback(null, results);
							    });
							} else {
								choose();
							}
						});
					} else {
						if(cache.get('notorrent') === true)
							callback(null, client);
						else
						    torrent[client](function(err, results) {
						    	callback(null, results);
						    });
					}
				});
			}

			choose(callback);
			
		}
	}
};

var password = {
	rutorrent : function(username, password, done) {
		var shell_path = pathInfo.join(__dirname,'/app/scripts/rutorrent/password.sh');

		execFile(shell_path, [username, password], function(err, stdout, stderr) {
			db.users.update(username, {password : password}, done);
		});

	},
	transmission : function(username, password, done) {
		//stopping daemon
		daemon('transmission', 'stop', username, function() {
			var shell_path = pathInfo.join(__dirname,'/app/scripts/transmission/password.sh');

			execFile(shell_path, [username, password], function(err, stdout, stderr) {

				var settings = __dirname + '/app/scripts/transmission/config/settings.'+username+'.json';

				var d = jf.readFileSync(settings);

				d['rpc-password'] = password;

				jf.writeFileSync(settings, d);

				//restarting daemon
				daemon('transmission', 'start', username, function() {
					db.users.update(username, {password : password}, done);
				});

			});
		});
	},
	aucun : function(username, password, done) {
		db.users.update(username, {password : password}, done);
	}
}

var resetWatcher = function(cb) {
	exec('pm2', ['restart', 'watcher'], function() {
		return typeof cb == 'function' ? cb() : true;
	});
}


var daemon = function(client, command, username, done) {
	var shell_path = pathInfo.join(__dirname,'/app/scripts/', client,'/daemon.sh');
	fs.chmodSync(shell_path, '775');

	var running = spawn(shell_path, [command, username]);

	running.stdout.on('data', function (data) {
		var string = new Buffer(data).toString();
		console.log(string.info);
	});

	running.stderr.on('data', function (data) {
		var string = new Buffer(data).toString();
		console.log(string.error);
		
	});

	running.on('exit', function (code) {
		if(typeof done == 'function')
			done();
		else
			process.exit(code);
	});
}

var reboot = function() {
	var start = function(user, cb) {
		daemon(user.client, 'start', user.username, function() {
			console.info(user.username + " " + user.client + " started");
			cb();
		});
	}

	db.users.getAll(function(err, users) {
		async.each(users, start, function(err){
			process.exit(0);
		});
	});
}

program
	.command('config')
	.option('-u, --skipuser', 'Skip admin creation')
	.option('-n, --notorrent', 'Skip torrent client installation')
	.option('-s, --skipnginx', 'Skip nginx configuration')
	.action(function(options) {
		
		cache.put('force', true);
		
		if(options.notorrent)
			cache.put('notorrent', true);

		if(options.skipnginx)
			cache.put('skipnginx', true);

		if(options.skipuser)
			cache.put('skipuser', true);

		cache.put('isinstall', true);

		async.series(install,
		function(err, results) {
			if(results.client_torrent === null) {
				console.log("Aucun client torrent spécifié, fin de l'installation".info);
				console.log("Vous pouvez maintenant démarrer ezseed pm2 start ezseed.json !".info);
				process.exit(1);
			} else {

				console.log("Création du compte " + results.client_torrent + " pour l'administrateur".info);

				//Création de l'admin
				cache.put('role', 'admin');
				
				var u = cache.get('user');

				useradd[results.client_torrent](u.username, u.password, function() {
					db.users.update(u.username, {client : results.client_torrent}, function(err) {
						cache.clear();
						console.log("Vous pouvez maintenant démarrer ezseed ! pm2 start ezseed.json".info);
						process.exit(1);
					});
				});
			}
		  
		});
	});

program
	.command('install [client]')
	.description('Installation du client torrent')
	.action(function(client) {

		install.client_torrent(function(err, obj) {
			cache.clear();
			console.log('Client torrent installé'.info);
			process.exit(1);
		}, client);
	});

program
	.command('update')
	.description('Update ezseed')
	.action(function() {
		exec('git pull && npm install && pm2 restart all', function(error) {
			console.log('Ezseed est à jour'.info);
			process.exit(1);
		});
	});

program
	.command('useradd <rutorrent|transmission|aucun> <username>')
	.option('-p, --password [password]', 'specify password')
	.option('-P, --path [path]', 'specify userdir path [depreceated]')
	.option('-r, --role <role>', '<admin|[user]>')
	.description("Ajout d'un utilisateur au client spécifié")
	.action(function(client, username, options) {

		if(fs.existsSync('./app/config.json')) {
			var config = jf.readFileSync('./app/config.json');

			if(client == "aucun" || config[client] == true) {

				if(options.path)
					cache.put('path', options.path);

				cache.put('force', true);

				var next = function(options) {

					if(options.password === undefined) {
						promptly.password('Mot de passe :', function(err, pw) {
							useradd[client](username, pw, function() {
								resetWatcher(function() {
									cache.clear();
									process.exit(1);
								});
							});
						});
					} else 
						useradd[client](username, options.password, function() {
							resetWatcher(function() {
								cache.clear();
								process.exit(1);
							});
						});
				};

				if(options.role) {

					if(options.role.length) {
						cache.put('role', role);
						next(options);
					} else {
						promptly.choose('Choisissez le role utilisateur {user|admin} : ', ['user', 'admin'], {default : 'user'}, function (err, role) {
							cache.put('role', role);
							next(options);
						});
					}
				} else
					next(options);

				
			} else {
				console.log("Le client " + client + " n'est pas installé !".error);
				process.exit(0);
			}
		} else {
			console.log("Le fichier de configuration n'existe pas, lancez ./ezseed install".error);
			process.exit(0);
		}

	});

program
	.command('userdel <rutorrent|transmission> <username>')
	.description("Suppression de l'utilisateur /!\\ tous les fichiers seront supprimés")
	.action(function(client, username, options) {
		cache.put('force', true);

		userdel[client](username, function() {
			process.exit(1);
		});
	});

program
	.command('password <rutorrent|transmission> <username> ')
	.option('-p, --password [password]', 'specify password')
	.description('Change username password')
	.action(function(client, username, options) {

		if(options.password === undefined) {
			promptly.password('Mot de passe :', function(err, pw) {
				password[client](username, pw, function() {
					cache.clear();
					process.exit(1);
				});
			});
		} else {
			password[client](username, options.password, function() {
				cache.clear();
				process.exit(1);
			});
		}
	})

program
	.command('daemon <rutorrent|transmission> <command> <username>')
	.description('start|stop|restart daemon-client for specified username')
	.action(daemon);

program
	.command('reboot')
	.description('Restart all daemons')
	.action(reboot);

mongoose.connect('mongodb://localhost/ezseed');

var mongo = mongoose.connection;

mongo.on('error', console.error.bind(console, 'connection error:'.error));
mongo.once('open', function callback () {
	program.parse(process.argv);
	if (!program.args.length) program.help();
});

// module.exports = {useradd : useradd};
